### ISSUE TITLE
كل الشكر لك على هذ الشرح الرائع لدي مشكلة بسيطة

### ISSUE THREAD

**Issue by Muhammed-Hayr-Ali** [UsamaElgendy/Ecommerce_App#2]
يظهر لي تنبيه بوجود خطأ
Restarted application in 3,341ms.
[38;5;244m[GETX] [39;49m"GetMaterialController" has been initialized
[38;5;244m[GETX] [39;49m"AuthViewModel" has been initialized
[38;5;244m[GETX] [39;49m"ControlViewModel" has been initialized
[38;5;244m[GETX] [39;49m"HomeViewModel" has been initialized

**W/DynamiteModule( 8567): Local module descriptor class for providerinstaller not found.
D/ConnectivityManager( 8567): requestNetwork and the calling app is: com.market.pro.marketna
W/et.pro.marketn( 8567): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
W/et.pro.marketn( 8567): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
W/et.pro.marketn( 8567): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
I/DynamiteModule( 8567): Considering local module providerinstaller:0 and remote module providerinstaller:0
W/ProviderInstaller( 8567): Failed to load providerinstaller module: No acceptable module found. Local version is 0 and remote version is 0.
D/ConnectivityManager( 8567): requestNetwork and the calling app is: com.market.pro.marketna
W/et.pro.marketn( 8567): Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
I/chatty  ( 8567): uid=11177(com.market.pro.marketna) FirestoreWorker identical 2 lines
W/et.pro.marketn( 8567): Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
W/et.pro.marketn( 8567): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
W/et.pro.marketn( 8567): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
W/et.pro.marketn( 8567): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
W/et.pro.marketn( 8567): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
W/et.pro.marketn( 8567): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
W/et.pro.marketn( 8567): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
W/et.pro.marketn( 8567): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
W/et.pro.marketn( 8567): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
W/et.pro.marketn( 8567): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
W/et.pro.marketn( 8567): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
W/et.pro.marketn( 8567): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
W/et.pro.marketn( 8567): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
W/et.pro.marketn( 8567): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
W/et.pro.marketn( 8567): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
W/et.pro.marketn( 8567): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
W/et.pro.marketn( 8567): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
W/et.pro.marketn( 8567): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
W/et.pro.marketn( 8567): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
W/et.pro.marketn( 8567): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
W/et.pro.marketn( 8567): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed)
W/et.pro.marketn( 8567): Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
I/chatty  ( 8567): uid=11177(com.market.pro.marketna) FirestoreWorker identical 8 lines
W/et.pro.marketn( 8567): Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
I/flutter ( 8567): 1
I/flutter ( 8567): 2
I/flutter ( 8567): 3
W/et.pro.marketn( 8567): Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
W/et.pro.marketn( 8567): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
W/et.pro.marketn( 8567): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
W/et.pro.marketn( 8567): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
W/et.pro.marketn( 8567): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)**

**Comment by usamaaelgendy** [comment]
solved !!
